"""Generated by @rules_apt//apt/private:repository.bzl"""

load("@rules_apt//apt/private:utils.bzl", "debfile_target", "debfile_layer_target", "package_target", "package_layer_target")

_REPOSITORY = "{REPOSITORY}"

_DEFAULT_DISTRO = "{DEFAULT_DISTRO}"

_DEFAULT_ARCH = "{DEFAULT_ARCH}"

def debfile(name, distro = _DEFAULT_DISTRO, arch = _DEFAULT_ARCH):
    return debfile_target(_REPOSITORY, name, distro, arch)

def debfile_layer(name, distro = _DEFAULT_DISTRO, arch = _DEFAULT_ARCH):
    return debfile_layer_target(_REPOSITORY, name, distro, arch)

def debian_package(name, distro = _DEFAULT_DISTRO, arch = _DEFAULT_ARCH):
    return package_target(_REPOSITORY, name, distro, arch)

def debian_package_layer(name, distro = _DEFAULT_DISTRO, arch = _DEFAULT_ARCH):
    return package_layer_target(_REPOSITORY, name, distro, arch)
